services:
  ansible:
    build: .
    container_name: ansible-hw4
    volumes:
      - ./playbook:/ansible/playbook
      - ./sshcp:/root/.ssh-mounted:ro
    working_dir: /ansible/playbook
    stdin_open: true
    tty: true
    networks:
      - ansible-network-hw4

networks:
  ansible-network-hw4:
    driver: bridge
