---
all:
  vars:
    ansible_connection: ssh
    ansible_user: ubuntu
    ansible_ssh_private_key_file: /root/.ssh/id_ed25519

  children:
    clickhouse:
      hosts:
        clickhouse-01:
          ansible_host: 158.160.96.222

    vector:
      hosts:
        vector-01:
          ansible_host: 158.160.35.223

    lighthouse:
      hosts:
        lighthouse-01:
          ansible_host: 51.250.94.16
